## string constant use multiple times in repositories

## DEA utils
LAMBDA = "lambda"
INPUT_ORIENT = "IO"
OUTPUT_ORIENT = "OO"
VRS = "vrs"
NIRS = "nirs"
NDRS = "ndrs"
## columns of df
INSURANCE_EXP = "insurance expenses"
OPERATION_EXP = "operation expenses"
UNDERWRITING_PROFIT = "underwriting profit"
INVESTMENT_PROFIT = "investment profit"
EFFICIENCY = "efficiency"
SCALE = "scale"
PROFIT = "profit "
OUT_DIR = "output progress direction"
REF_DMU = "reference DMU"
REF_LAMBDA = "reference lambda"
INSURANCE_MAXDMP = "insurance_exp max direction of MP"
INSURANCE_COS_SIM = "insurance_exp cosine similarity"
OPERATION_MAXDMP = "operation_exp max direction of MP"
OPERATION_COS_SIM = "operation_exp cosine similarity"
COS_SIM = "overall cosine similarity"
EC = "efficiency changing"